name: Release

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - uses: googleapis/release-please-action@v4
      id: release
      with:
        release-type: simple
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Make release zipball
      if: ${{ steps.release.outputs.release_created }}
      run: |
        # Create captain directory structure
        mkdir -p release/captain
        
        # Copy all repo content to captain folder (excluding .git and .github)
        rsync -av --exclude='.git' --exclude='.github' --exclude='captures' ./ release/captain/
        
        # Create the zip file
        cd release
        zip -r ../captain.zip captain/
        cd ..
        
        # Verify zip contents
        echo "Zip file contents:"
        unzip -l captain.zip | head -20

    - name: Upload Release Artifact
      if: ${{ steps.release.outputs.release_created }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release upload ${{ steps.release.outputs.tag_name }} captain.zip
