name: Release

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    # - uses: googleapis/release-please-action@v4
    #   id: release
    #   with:
    #     release-type: simple
    #     token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build SQLite3 DLL (32-bit)
      # if: ${{ steps.release.outputs.release_created }}
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW32
        update: true
        install: >-
          mingw-w64-i686-gcc
          mingw-w64-i686-sqlite3
          mingw-w64-i686-pkg-config
          make
    
    - name: Compile SQLite3 DLL
      # if: ${{ steps.release.outputs.release_created }}
      shell: msys2 {0}
      run: |
        # Create deps directory
        mkdir -p deps
        
        # Download SQLite3 source for static compilation
        curl -o sqlite3.zip https://sqlite.org/2024/sqlite-amalgamation-3460100.zip
        unzip sqlite3.zip
        cd sqlite-amalgamation-3460100
        
        # Build fully static 32-bit SQLite3 DLL for Windows
        i686-w64-mingw32-gcc -shared -o ../deps/sqlite3.dll \
          sqlite3.c \
          -DSQLITE_ENABLE_FTS5 \
          -DSQLITE_ENABLE_JSON1 \
          -DSQLITE_ENABLE_RTREE \
          -static-libgcc \
          -Wl,--out-implib,../deps/libsqlite3.dll.a \
          -Wl,--no-undefined
        
        cd ..
        rm -rf sqlite3.zip sqlite-amalgamation-3460100

    - name: Fetch dependencies
      # if: ${{ steps.release.outputs.release_created }}
      run: |
        # Create deps directory
        mkdir -p deps
        
        # Fetch serpent.lua
        curl -o deps/serpent.lua https://raw.githubusercontent.com/pkulchenko/serpent/refs/heads/master/src/serpent.lua
        
        # Fetch json.lua
        curl -o deps/json.lua https://raw.githubusercontent.com/rxi/json.lua/refs/heads/master/json.lua
        
        # Fetch copas 4.8.0
        curl -L -o copas.zip https://github.com/lunarmodules/copas/archive/refs/tags/4.8.0.zip
        unzip copas.zip
        cp -r copas-4.8.0/src/* deps/
        rm -rf copas.zip copas-4.8.0
        
        # Fetch lua-websockets v2.2
        curl -L -o lua-websockets.zip https://github.com/lipp/lua-websockets/archive/refs/tags/v2.2.zip
        unzip lua-websockets.zip
        cp -r lua-websockets-2.2/src/* deps/
        rm -rf lua-websockets.zip lua-websockets-2.2

    - name: Make release zipball
      # if: ${{ steps.release.outputs.release_created }}
      run: |
        # Create captain directory structure
        mkdir -p release/captain
        
        # Copy all repo content to captain folder (excluding .git and .github)
        rsync -av --exclude='.git' --exclude='.github' --exclude='captures' ./ release/captain/
        
        # Create the zip file
        cd release
        zip -r ../captain.zip captain/
        cd ..
        
        # Verify zip contents
        echo "Zip file contents:"
        unzip -l captain.zip | head -20

    - name: Upload Release Artifact
      # if: ${{ steps.release.outputs.release_created }}
      # env:
      #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # run: gh release upload ${{ steps.release.outputs.tag_name }} captain.zip
      run: |
        echo "Would upload captain.zip here"
        ls -la captain.zip
